frontend/src/components/AboutModal.jsx, frontend/src/components/Header.jsx, frontend/src/components/LeftSidebar.jsx, frontend/src/constants.js, frontend/src/images/svg/close.svg, frontend/src/images/svg/toggle-in.svg, frontend/src/images/svg/toggle.svg, frontend/src/pages/NeuroScan.jsx, frontend/src/pages/PromoterDB.jsx, frontend/src/styles/constants.js, frontend/src/theme.js
@lrebscher Please merge feature/28 before merging this one with develop
=> Feature/51 - About Modal for neuroscan and promoter db

applications/neuroscan/frontend/src/components/Chart/CameraControls.jsx, applications/neuroscan/frontend/src/components/Chart/MenuControl.jsx, applications/neuroscan/frontend/src/components/Chart/capture-menu/CaptureControls.jsx, applications/neuroscan/frontend/src/components/Chart/capture-menu/DownloadMenu.jsx, applications/neuroscan/frontend/src/components/Chart/capture-menu/RecordControlModal.jsx, applications/neuroscan/frontend/src/flexLayout.css, applications/neuroscan/frontend/src/utilities/constants.js, applications/neuroscan/frontend/src/utilities/functions.js
Depends on MetaCell/geppetto-meta#191
- Moves download button from camera controls to captureControls
- Adds download screenshot feature
=> #107 Adds download screenshot feature

applications/neuroscan/frontend/src/components/Chart/capture-menu/CaptureControls.jsx, applications/neuroscan/frontend/src/services/ZipService.js, applications/neuroscan/frontend/src/utilities/functions.js
implements obj download as zip from #107
=> #107 chore: implement viewer instances download

applications/neuroscan/frontend/src/pages/PromoterDB.jsx, applications/neuroscan/frontend/src/theme.js
This should be merged after feature/209 since it has been based on that branch!
=> PromoterDB black background

applications/neuroscan/frontend/src/pages/PromoterDB.jsx, applications/neuroscan/frontend/src/theme.js
the branch was based on feature/209 (cosmetic changes Pr)
=> PromoterDB black UI

applications/neuroscan/frontend/src/pages/PromoterDB.jsx, applications/neuroscan/frontend/yarn.lock
=> #284 Update promoter filter

applications/neuroscan/frontend/src/redux/middleware.js
=> #283 Update cphate slider

applications/neuroscan/frontend/package.json
Uses custom made stable geppetto-meta-ui version
=> #297 chore: Update geppetto-meta-ui version

applications/neuroscan/frontend/package.json
=> #301 chore: Update geppetto-meta-ui version

applications/neuroscan/frontend/src/components/Sidebar/Search.jsx
- manage copy and pasting from an excel file to separate text by spaces, commas into separated tags
=> #23 handle pasting text to search input

applications/neuroscan/frontend/package.json, applications/neuroscan/frontend/src/App.css, applications/neuroscan/frontend/src/components/Header.jsx
- for the first time that user opens the app this tutorial will be displayed, and if clicked on dont show again, then there is a cookie is stored in cookies storage and this tutorial will not appear again 
- if user clicked on tutorial from the hamburger menu, the tutorial will be displayed but without the dont show again checkbox
=> #15 add the dont show again message to the tutorial

applications/neuroscan/frontend/src/components/Chart/MenuControl.jsx, applications/neuroscan/frontend/src/services/NeuronService.js
- fix getByUID query to remove the added comma which affects the viewer instances 
- fix the initial slider timepoint  for the new viewers
attached a video recording for the 2 fixes 
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/32265731/86ee5e16-e91f-4008-a798-fd7568caab0e
=> #2 fix slider issue

applications/neuroscan/frontend/src/components/Chart/ControlMenus/ColorPickerMenu.jsx, applications/neuroscan/frontend/src/components/Sidebar/Explorer/Explorer.jsx, applications/neuroscan/frontend/src/services/instanceHelpers.js
related to this [comment](https://metacell.atlassian.net/browse/YALE-13?focusedCommentId=11358)
- sort the outer array of grouped instances
=> #13 sort grouped instances

applications/neuroscan/frontend/src/components/Sidebar/AddToViewerMenu.jsx
- fix disabling synapses after adding them to the viewer
=> #4 fix Search synapses not disabled

applications/neuroscan/frontend/package.json, applications/neuroscan/frontend/src/components/viewers/viewer.js, applications/neuroscan/frontend/yarn.lock
Requires: https://github.com/MetaCell/geppetto-meta/pull/515
Closes https://metacell.atlassian.net/browse/YALE-27
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/19196034/0309265c-170b-476b-825d-252d72e59696
=> YALE-27 feat: Add context menu to CPHATE

applications/neuroscan/frontend/src/components/Common/SearchResult.jsx, applications/neuroscan/frontend/src/components/LeftSidebar.jsx, applications/neuroscan/frontend/src/components/Sidebar/AddToViewerMenu.jsx, applications/neuroscan/frontend/src/components/Sidebar/Results.jsx
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/32265731/8e142261-3984-402e-8cef-e66dcd54610b
=> #19 add all buttons

applications/neuroscan/frontend/src/theme.js
Issue #YALE-21
Problem: Three dots frontend change
Solution: Just deleted hover styling for three dots and set none value to block for MuiIconButton
=> YALE-21 Three dots frontend change

applications/neuroscan/backend/api/contact/services/contact.js
Returns the complete contact properties on contacts fetch
=> YALE-12 fix: Retrieve all contact attributes on fetch

applications/neuroscan/backend/api/contact/services/contact.js, applications/neuroscan/frontend/src/components/Chart/capture-menu/highlight/HighlightPopover.js, applications/neuroscan/frontend/src/components/Sidebar/Search.jsx
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/32265731/0652cb5f-9732-4267-bd8d-85d28a289344
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/32265731/d697aac2-2831-41f9-9957-aad6a0bad686
=> fix empty search, adding contacts issue

applications/neuroscan/backend/api/contact/controllers/contact.js, applications/neuroscan/backend/api/contact/services/contact.js, applications/neuroscan/frontend/src/components/Chart/capture-menu/CaptureControls.jsx, applications/neuroscan/frontend/src/components/Sidebar/Explorer/ExplorerMenu.jsx, applications/neuroscan/frontend/src/components/Sidebar/Explorer/TreeItem.jsx, applications/neuroscan/frontend/src/components/viewers/viewer.js, applications/neuroscan/frontend/src/redux/actions/widget.js, applications/neuroscan/frontend/src/redux/middleware.js, applications/neuroscan/frontend/src/redux/reducers/all.js, applications/neuroscan/frontend/src/redux/reducers/selectedInstanceToDelete.js, applications/neuroscan/frontend/src/redux/store.js, applications/neuroscan/frontend/src/services/instanceHelpers.js
- Only fetch data on timepoint change if the there's at least one entity of a given entity type (neurons, contacts, synapses)
- Change the contacts find endpoint to use the default strapi find unless terms are defined
- Set default contacts name
- Updates contacts sorting strategy
https://github.com/MetaCell/geppetto-NeuroSCAN/assets/19196034/bebbed29-701a-4903-9a03-af53525354cf
=> fix: Fix incorrect data fetching on viewer timepoint change
